import Head from 'next/head';
import React, { use, useState } from 'react';
import styles from '../styles/Home.module.css'; 
import { Configuration,OpenAIApi } from "openai";

export default function Home() {
  const [message,setMessage] = useState("");
  const [messages,setMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(false);


  const configuration = new Configuration({
    apiKey: process.env.NEXT_PUBLIC_OPENAPI_KEY,
  });

  const openai = new OpenAIApi(configuration);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

   const response = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages:[{role: "user", content: "こんにちは" }],
    });

    console.log(response.choices[0].message?.content);
  };


  return (
  <div className= {styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className='flex flex-col items-center justify-center h-screen'>
      <div className="max-w-lg w-full">
        <div
        style={{height: "650px"}}
        className='bg-gray-100 w-full p-4 h-96 overflow-scroll rounded-lg'>
          <span className="text-center block font-medium text-2x1 border-b-2 border-indigo-400">ジーニアス山崎</span>

          <div className="flex justify-end mb-2">
            <div className="bg-indigo-400 text-white p-2 rounded-md">hello</div>
          </div>
          <div className="flex justify-start mb-2">
            <div className="bg-gray-200 p-2 rounded-md">やっほー</div>
          </div>
        </div>



        <form className="w-full" onSubmit={(e) => handleSubmit(e)}>
          <div className="flex item-center p-4 bg-gray-100 rounded-lg w-full">
            <input type="text" className="flex-1 border-2 py-2 px-4 focus:outline-none rounded-lg focus:border-indigo-400"></input>
            <button type="submit" className="p-2 bg-indigo-400 rounded-lg text-white hover:bg-indigo-500">
              {isLoading ? "天才の解答待ち":"相談"}
              </button>
          </div>
        </form>

      </div>
    </div>
  </div>
  );
}
